drop table if exists tantangan.nasabah;

--perintah CREATE
create table tantangan.nasabah(
	id int generated by default as identity,
	nama varchar(100) not null,
	alamat varchar(100) not null,
	email varchar(100) not null,
	phone int,
	primary key(id)
);


drop table if exists tantangan.akun;
create table tantangan.akun(
id int generated by default as identity,
nama varchar (100) not null,
balance dec(15,2) not null
);


-- perintah drop
drop table if exists tantangan.transaksi;

create table tantangan.transaksi(
id int generated by default as identity,
amount dec (15,2) not null,
tipe varchar (100)not null,
time timestamp NOT NULL

);



/*informasi nasabah*/
insert into tantangan.nasabah(id,nama,alamat,email,phone)
values
(1,'andika','yogya','andika.pw2634@gmail.com',0822),
(2,'andika','NEW yORK','andika.pw2634@gmail.com',6256),
(3,'Vill-V','palembang','andika.pw2634@gmail.com',6211);


insert into tantangan.akun(id,nama,balance)
values 
(11,'Archeron',700000),
(22,'Ely',300000),
(33,'kiana',600000);


insert into tantangan.transaksi(id,amount,tipe,time)
values 
(777,545000,'Qris','2024-8-05 15:45:00'),
(333,500000,'setor',now()),
(444,900000,'Qris','2024-10-07 11:45:00');


-- perintah READ
select * from tantangan.akun;
select * from tantangan.transaksi;
select * from tantangan.nasabah;


-- perintah UPDATE 
UPDATE tantangan.nasabah
SET nama = 'Jane Doe', email = 'jane.doe@email.com'
WHERE ID = 2;

select * from tantangan.nasabah;



-- perintah DELETE
delete from tantangan.akun 
where id=22;

select * from tantangan.akun;




-- left join
SELECT c.*,o.*
FROM tantangan.nasabah c
left JOIN tantangan.akun  o
ON c.id = o.id;


--right join
SELECT c.*,o.*
FROM tantangan.nasabah c
right JOIN tantangan.akun  o
ON c.id = o.id;

-- full join
SELECT c.*,o.*
FROM tantangan.nasabah c
full JOIN tantangan.akun  o
ON c.id = o.id;



